### ISSUE TITLE
Website Returns a 400 response code

### ISSUE THREAD

**Issue by devpranoy** [biswaz/rescuekerala#3]
I think your heroku dyno has expired due to the heavy traffic. Please shift the project to AWS or Digital Ocean or upgrade the dyno. Make sure to thread the app while it's running on production.

**Comment by biswaz** [comment]
I had not added www. in allowed_hosts. Fixed. 
Can you explain the threading part?

**Comment by devpranoy** [comment]
Ohh no worries about the threading, Django takes care of it. In Flask tho you need to specify that it has to be threaded otherwise it would not serve multiple user-requests at the same time.
